apiVersion: batch/v1
kind: Job
metadata:
  name: canihazconnection
spec:
  template:
    spec:
      containers:
      - name: canihazconnection
        image: ############## IMAGE URL HERE ###################
        imagePullPolicy: Always
        env:
          - name: TELNET_HOSTS
            value: |-
              google.com:80,
              facebook.com:80,
              twitter.com:80
          - name: HTTP_REQUESTS
            value: |-
              https://google.com,
              https://facebook.com,
              https://twitter.com
          - name: LOG_LEVEL
            value: DEBUG
      restartPolicy: Never
  backoffLimit: 0
